apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9oaXNoYW1tcHNuOnk3U0l3dHd6bDhrWlhxUHVAY2x1c3RlcjAuZXV4c3AubW9uZ29kYi5uZXQvcG9zdF9kYj9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
  SECRET: c2VjcmV0
  EMAIL_ID: aGlzaGFtbXBzbkBnbWFpbC5jb20=
  PASS_KEY: aGlzaGFtbXBzbkBnbWFpbC5jb20=
