apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::235494819343:role/eksctl-view-net-cluster-nodegroup--NodeInstanceRole-Kl5agY9xx9TZ
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::235494819343:user/video_uploader
      username: video_uploader
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2025-02-22T13:29:35Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1448"
  uid: 06f03e4d-2966-45ad-8b5d-6e2617c2c703