apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-gateway-cert
spec:
  secretName: api-gateway-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - api.viewnet.cfd
