name: deploy-live-streaming-service
on:
  push:
    branches:
      - master
    paths:
      - "live-streaming-service/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push API live-streaming-service Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/view_net-live-streaming-service:latest ./live-streaming-service
          docker push ${{ secrets.DOCKER_USERNAME }}/view_net-live-streaming-service:latest


  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up kubectl
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Deploy Live Streaming Service
        run: |
          kubectl apply -f ./k8s/live-streaming-service.yaml
          kubectl rollout restart deployment live-streaming-service
